# Use root/example as user/password credentials
version: '3.1'

services:

  app:
    image: node:lts-alpine
    depends_on:
      - database
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src:rw
    env_file:
      - .env
    network_mode: host
    command:
      - npx
      - nodemon
      - -L
      - app.js

  database:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql:/var/lib/mysql
      - ./app/resources/init.sql:/docker-entrypoint-initdb.d/1.sql
    network_mode: host

volumes:
  mysql: ~
